import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowLeft, CheckCircle2, FileUp, FileText, Clock3, Loader2, Mail, Package, ReceiptText, Store } from "lucide-react";
import { toast } from "sonner";

import { PortalHeader } from "@/components/portal-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { obterMeuAcesso } from "@/lib/admin.functions";
import { obterProtocolo, registrarDecisao, registrarNotaDevolucao } from "@/lib/protocolos.functions";
import { APROVACAO_LABEL, STATUS_CLASSE, STATUS_LABEL, STATUS_OPCOES, data, dataHora, moeda } from "@/lib/protocolo-ui";

export const Route = createFileRoute("/_authenticated/protocolos/$id")({
  head: () => ({ meta: [
    { title: "Análise do protocolo | Trebeschi" }, { name: "description", content: "Análise interna de uma solicitação de devolução." },
    { property: "og:title", content: "Análise do protocolo | Trebeschi" }, { property: "og:description", content: "Análise interna de uma solicitação de devolução." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: ProtocoloPage,
});

function ProtocoloPage() {
  const { id } = Route.useParams(); const obter = useServerFn(obterProtocolo); const consultarAcesso = useServerFn(obterMeuAcesso); const decidir = useServerFn(registrarDecisao); const [dados, setDados] = useState<Awaited<ReturnType<typeof obterProtocolo>> | null>(null); const [podeAnalisar, setPodeAnalisar] = useState(false); const [status, setStatus] = useState("em_analise"); const [parecer, setParecer] = useState(""); const [quantidades, setQuantidades] = useState<Record<string, number>>({}); const [salvando, setSalvando] = useState(false); const [aprovacao, setAprovacao] = useState(""); const enviarNf = useServerFn(registrarNotaDevolucao); const [nfAberto, setNfAberto] = useState(false); const [nfNumero, setNfNumero] = useState(""); const [nfArquivo, setNfArquivo] = useState<File | null>(null); const [enviandoNf, setEnviandoNf] = useState(false);
  async function carregar() { try { const [retorno, acesso] = await Promise.all([obter({ data: { id } }), consultarAcesso()]); setDados(retorno); setPodeAnalisar(acesso.roles.includes("admin") || acesso.roles.includes("analista")); setStatus(retorno.protocolo.status); setAprovacao(retorno.protocolo.aprovacao ?? ""); setParecer(retorno.protocolo.parecer ?? ""); setQuantidades(Object.fromEntries(retorno.itens.map((item) => [item.id, Number(item.quantidade_aceita ?? item.quantidade)]))); } catch { toast.error("Não foi possível carregar este protocolo."); } }
  useEffect(() => { carregar(); }, [id]);
  const valorAceito = useMemo(() => dados?.itens.reduce((s, item) => s + (quantidades[item.id] ?? 0) * Number(item.valor_unitario), 0) ?? 0, [dados, quantidades]);
  async function salvar(event: FormEvent) { event.preventDefault(); setSalvando(true); try { await decidir({ data: { id, status: status as "em_analise", aprovacao: (aprovacao || null) as "recusado" | null, parecer: parecer || null, quantidades: Object.entries(quantidades).map(([item_id, quantidade_aceita]) => ({ item_id, quantidade_aceita })) } }); toast.success("Análise salva e notificação registrada."); await carregar(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível salvar."); } finally { setSalvando(false); } }
  if (!dados) return <div className="min-h-screen"><PortalHeader interno /><p className="p-16 text-center text-muted-foreground">Carregando protocolo…</p></div>;
  const p = dados.protocolo;
  async function anexarNf(event: FormEvent) { event.preventDefault(); if (!nfArquivo) { toast.error("Selecione o PDF (DANFE) da nota fiscal."); return; } if (nfArquivo.type !== "application/pdf" && !nfArquivo.name.toLowerCase().endsWith(".pdf")) { toast.error("O arquivo deve ser PDF (DANFE)."); return; } if (nfArquivo.size > 10 * 1024 * 1024) { toast.error("O PDF deve ter no máximo 10 MB."); return; } setEnviandoNf(true); try { const buf = new Uint8Array(await nfArquivo.arrayBuffer()); let bin = ""; for (let i = 0; i < buf.length; i += 0x8000) bin += String.fromCharCode(...buf.subarray(i, i + 0x8000)); await enviarNf({ data: { id, nf_devolucao: nfNumero, pdf_base64: btoa(bin), nome_arquivo: nfArquivo.name } }); toast.success("Nota fiscal anexada."); setNfAberto(false); setNfArquivo(null); setNfNumero(""); await carregar(); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível anexar a nota."); } finally { setEnviandoNf(false); } }
  return <div className="min-h-screen"><PortalHeader interno /><main className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Voltar à fila</Link><div className="mt-5 flex flex-col justify-between gap-4 border-b pb-6 sm:flex-row sm:items-end"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold">{p.numero}</h1><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${STATUS_CLASSE[p.status] ?? "bg-muted"}`}>{STATUS_LABEL[p.status] ?? p.status}</span>{p.aprovacao && <span className="rounded-full border px-2.5 py-1 text-xs font-semibold">{APROVACAO_LABEL[p.aprovacao]}</span>}{p.status === "aguardando_nf" && <Button type="button" size="sm" onClick={() => setNfAberto(true)}><FileUp /> Anexar nota fiscal</Button>}</div><p className="mt-2 text-sm text-muted-foreground">Recebido em {dataHora(p.created_at)}</p></div><div className="text-left sm:text-right"><p className="text-xs uppercase text-muted-foreground">Valor solicitado</p><strong className="text-2xl">{moeda(p.valor_total)}</strong></div></div>
    <div className={`mt-8 grid gap-8 ${podeAnalisar ? "xl:grid-cols-[minmax(0,1fr)_390px]" : "grid-cols-1"}`}><div className="space-y-8"><section className="grid gap-px border bg-border sm:grid-cols-2 lg:grid-cols-4"><Info icon={<Store />} label="Loja" value={p.loja_nome} detail={p.loja_codigo} /><Info icon={<Mail />} label="Solicitante" value={p.cliente_nome} detail={p.cliente_email} /><Info icon={<ReceiptText />} label="Nota / Pedido" value={p.nota_fiscal || "Não informada"} detail={p.pedido || "Sem pedido"} /><Info icon={<Clock3 />} label="Data da compra" value={data(p.data_compra)} detail={p.cliente_telefone || "Sem telefone"} /></section>
      <section><Titulo icon={<Package />} texto="Produtos solicitados" /><div className="mt-4 overflow-x-auto border bg-card"><table className="w-full min-w-[720px] text-sm"><thead className="border-b bg-muted/60 text-left text-xs uppercase text-muted-foreground"><tr><th className="p-3">Produto</th><th className="p-3">Lote</th><th className="p-3">Solicitado</th><th className="p-3">Valor unit.</th><th className="p-3">Quantidade aceita</th></tr></thead><tbody>{dados.itens.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-3"><strong>{item.descricao}</strong><span className="block text-xs text-muted-foreground">{item.codigo_produto || "Sem código"} · {item.motivo || p.motivo}</span></td><td className="p-3">{item.lote || "—"}</td><td className="p-3">{item.quantidade} {item.unidade}</td><td className="p-3">{moeda(item.valor_unitario)}</td><td className="p-3">{podeAnalisar ? <Input aria-label={`Quantidade aceita de ${item.descricao}`} type="number" min="0" max={item.quantidade} step="0.01" className="w-28" value={quantidades[item.id] ?? 0} onChange={(e) => setQuantidades({ ...quantidades, [item.id]: Number(e.target.value) })} /> : <span>{item.quantidade_aceita ?? "Aguardando análise"}</span>}</td></tr>)}</tbody></table><div className="flex justify-end border-t bg-muted/30 p-4 text-sm"><span className="mr-4 text-muted-foreground">Valor aceito</span><strong>{moeda(valorAceito)}</strong></div></div></section>
      {(nfAberto || p.nf_devolucao) && <section><Titulo icon={<FileText />} texto="Nota fiscal de devolução" /><div className="mt-4 border bg-card p-5">{p.nf_devolucao && !nfAberto ? <div className="flex flex-wrap items-center gap-4 text-sm"><span>NF <strong>{p.nf_devolucao}</strong></span>{dados.nfUrl && <a href={dados.nfUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-primary underline"><FileText className="size-4" /> Abrir DANFE (PDF)</a>}</div> : <form onSubmit={anexarNf} className="grid gap-4 sm:grid-cols-[200px_1fr_auto] sm:items-end"><div><Label className="mb-2 block">Número da NF</Label><Input required value={nfNumero} onChange={(e) => setNfNumero(e.target.value)} /></div><div><Label className="mb-2 block">DANFE (PDF, até 10 MB)</Label><Input required type="file" accept="application/pdf,.pdf" onChange={(e) => setNfArquivo(e.target.files?.[0] ?? null)} /></div><div className="flex gap-2"><Button type="submit" disabled={enviandoNf}>{enviandoNf ? <Loader2 className="animate-spin" /> : <FileUp />} Salvar</Button><Button type="button" variant="outline" onClick={() => setNfAberto(false)}>Cancelar</Button></div></form>}</div></section>}
      <section><Titulo icon={<span className="text-sm font-bold">i</span>} texto="Ocorrência" /><div className="mt-4 border-l-2 border-primary bg-card p-5"><strong>{p.motivo}</strong><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{p.descricao || "Sem descrição adicional."}</p></div></section>
      <section><Titulo icon={<span className="text-sm font-bold">▣</span>} texto={`Evidências (${dados.fotos.length})`} /><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-3">{dados.fotos.map((foto, index) => foto.url ? <a key={foto.id} href={foto.url} target="_blank" rel="noreferrer" className="group overflow-hidden border bg-card"><img src={foto.url} alt={`Evidência ${index + 1}`} className="aspect-[4/3] w-full object-cover transition-transform group-hover:scale-[1.02]" /><p className="p-2 text-xs text-muted-foreground">Evidência {index + 1}</p></a> : <div key={foto.id} className="flex aspect-[4/3] items-center justify-center border bg-muted text-xs text-muted-foreground">Imagem expurgada</div>)}</div></section>
      <section><Titulo icon={<Clock3 />} texto="Histórico" /><div className="mt-4 border-l border-border pl-6">{dados.eventos.map((evento) => <div key={evento.id} className="relative pb-6 last:pb-0"><span className="absolute -left-[29px] top-1 size-3 rounded-full border-2 border-background bg-primary" /><p className="text-sm font-medium">{evento.descricao}</p><p className="mt-1 text-xs text-muted-foreground">{dataHora(evento.created_at)}{evento.autor_nome ? ` · ${evento.autor_nome}` : ""}</p></div>)}</div></section></div>
      {podeAnalisar && <aside className="xl:sticky xl:top-6 xl:self-start"><form onSubmit={salvar} className="border bg-card shadow-sm"><div className="border-b bg-primary p-5 text-primary-foreground"><p className="text-xs font-semibold uppercase tracking-widest text-primary-foreground/65">Atendimento</p><h2 className="mt-1 text-xl font-bold">Registrar análise</h2></div><div className="space-y-5 p-5"><div><Label className="mb-2 block">Situação</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={status} onChange={(e) => setStatus(e.target.value)}>{STATUS_OPCOES.map((s) => <option key={s} value={s}>{STATUS_LABEL[s]}</option>)}</select></div><div><Label className="mb-2 block">Aprovação</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={aprovacao} onChange={(e) => { setAprovacao(e.target.value); if (e.target.value === "recusado") setStatus("recusado"); else if (e.target.value) setStatus("aguardando_nf"); }}><option value="">Sem decisão</option>{Object.entries(APROVACAO_LABEL).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div><div><Label className="mb-2 block">Parecer para o cliente</Label><Textarea rows={7} value={parecer} onChange={(e) => setParecer(e.target.value)} placeholder="Explique a decisão e os próximos passos." /></div><div className="border-l-2 border-primary bg-primary/5 p-3 text-xs text-muted-foreground"><strong className="block text-foreground">Notificação por e-mail</strong>Ao salvar, a resposta será registrada para envio ao cliente.</div><Button type="submit" size="lg" className="w-full" disabled={salvando}>{salvando ? <Loader2 className="animate-spin" /> : <CheckCircle2 />} Salvar análise</Button></div></form></aside>}</div>
  </main></div>;
}
function Info({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string | null }) { return <div className="bg-card p-4"><span className="text-primary [&_svg]:size-4">{icon}</span><p className="mt-3 text-xs uppercase text-muted-foreground">{label}</p><strong className="mt-1 block text-sm">{value}</strong><p className="mt-1 truncate text-xs text-muted-foreground">{detail || "—"}</p></div>; }
function Titulo({ icon, texto }: { icon: React.ReactNode; texto: string }) { return <div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-md bg-secondary text-primary [&_svg]:size-4">{icon}</span><h2 className="text-lg font-bold">{texto}</h2><span className="h-px flex-1 bg-border" /></div>; }