/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnaliseRouteImport } from './routes/_authenticated/analise'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNovaSolicitacaoRouteImport } from './routes/_authenticated/nova-solicitacao'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedAnaliseIdRouteImport } from './routes/_authenticated/analise.$id'
import { Route as AuthenticatedProtocolosIdRouteImport } from './routes/_authenticated/protocolos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnaliseRoute = AuthenticatedAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaSolicitacaoRoute =
  AuthenticatedNovaSolicitacaoRouteImport.update({
    id: '/nova-solicitacao',
    path: '/nova-solicitacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnaliseIdRoute = AuthenticatedAnaliseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAnaliseRoute,
} as any)
const AuthenticatedProtocolosIdRoute =
  AuthenticatedProtocolosIdRouteImport.update({
    id: '/protocolos/$id',
    path: '/protocolos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analise': typeof AuthenticatedAnaliseRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nova-solicitacao': typeof AuthenticatedNovaSolicitacaoRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/analise/$id': typeof AuthenticatedAnaliseIdRoute
  '/protocolos/$id': typeof AuthenticatedProtocolosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analise': typeof AuthenticatedAnaliseRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nova-solicitacao': typeof AuthenticatedNovaSolicitacaoRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/analise/$id': typeof AuthenticatedAnaliseIdRoute
  '/protocolos/$id': typeof AuthenticatedProtocolosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analise': typeof AuthenticatedAnaliseRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/nova-solicitacao': typeof AuthenticatedNovaSolicitacaoRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/analise/$id': typeof AuthenticatedAnaliseIdRoute
  '/_authenticated/protocolos/$id': typeof AuthenticatedProtocolosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/analise'
    | '/dashboard'
    | '/nova-solicitacao'
    | '/solicitacoes'
    | '/analise/$id'
    | '/protocolos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/analise'
    | '/dashboard'
    | '/nova-solicitacao'
    | '/solicitacoes'
    | '/analise/$id'
    | '/protocolos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/analise'
    | '/_authenticated/dashboard'
    | '/_authenticated/nova-solicitacao'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/analise/$id'
    | '/_authenticated/protocolos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise': {
      id: '/_authenticated/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AuthenticatedAnaliseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-solicitacao': {
      id: '/_authenticated/nova-solicitacao'
      path: '/nova-solicitacao'
      fullPath: '/nova-solicitacao'
      preLoaderRoute: typeof AuthenticatedNovaSolicitacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise/$id': {
      id: '/_authenticated/analise/$id'
      path: '/$id'
      fullPath: '/analise/$id'
      preLoaderRoute: typeof AuthenticatedAnaliseIdRouteImport
      parentRoute: typeof AuthenticatedAnaliseRoute
    }
    '/_authenticated/protocolos/$id': {
      id: '/_authenticated/protocolos/$id'
      path: '/protocolos/$id'
      fullPath: '/protocolos/$id'
      preLoaderRoute: typeof AuthenticatedProtocolosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAnaliseRouteChildren {
  AuthenticatedAnaliseIdRoute: typeof AuthenticatedAnaliseIdRoute
}

const AuthenticatedAnaliseRouteChildren: AuthenticatedAnaliseRouteChildren = {
  AuthenticatedAnaliseIdRoute: AuthenticatedAnaliseIdRoute,
}

const AuthenticatedAnaliseRouteWithChildren =
  AuthenticatedAnaliseRoute._addFileChildren(AuthenticatedAnaliseRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnaliseRoute: typeof AuthenticatedAnaliseRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNovaSolicitacaoRoute: typeof AuthenticatedNovaSolicitacaoRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedProtocolosIdRoute: typeof AuthenticatedProtocolosIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnaliseRoute: AuthenticatedAnaliseRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNovaSolicitacaoRoute: AuthenticatedNovaSolicitacaoRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedProtocolosIdRoute: AuthenticatedProtocolosIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
